// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ3TywwGf3hRsXAWQlRiEwY75QJ87bq34',
    appId: '1:153094232706:web:4864458e65eaf2aa96729b',
    messagingSenderId: '153094232706',
    projectId: 'appis-app',
    authDomain: 'appis-app.firebaseapp.com',
    storageBucket: 'appis-app.appspot.com',
    measurementId: 'G-HG1SJSH7RE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_HPnkeY5AP7bj5NumtxxAMemSfAGUowc',
    appId: '1:153094232706:android:4e4544847ac6d00a96729b',
    messagingSenderId: '153094232706',
    projectId: 'appis-app',
    storageBucket: 'appis-app.appspot.com',
  );

}